version: '3.9'
services:
  app:
    image: python:3.10
    build: .
    ports:
      - "3000:80"
    command: "uvicorn app.main:app --host 0.0.0.0 --port 80"
  db:
    image: couchbase:latest
    deploy:
      replicas: 1
    ports:
      - 8091:8091
