version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.local
    ports:
      - "3000:80"
    depends_on:
      - db
  db:
    image: couchbase:latest
    ports:
      - "8091-8095:8091-8095"
      - "9102:9102"
      - "11210:11210"
    expose:
      - "8091"
      - "8092"
      - "8093"
      - "8094"
      - "8095"
      - "9102"
      - "11210"
